# Project Information
site_name: Hospital Ebayes 
site_description: Hospital Provider ID Crosswalk 
site_author: cooper-lab
site_url: https://fictional-adventure-8q8z4q4.pages.github.io/
docs_dir: docs
site_dir: site


# Repository
repo_name: hospital_ebayes
repo_url: https://github.com/daltonmaurice/hospital_ebayes
edit_uri:  edit/main/docs/
#dev_addr: 0.0.0.0:4040

# Important for correct viewing offline
use_directory_urls: false


theme:
  palette:
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto Serif
    code: Roboto Mono
  name: material
  icon:
    edit: material/pencil
    view: material/eye

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.sections
    - content.action.edit
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tabs.stick
    - navigation.indexes
    - content.code.copy
    - navigation.footer


# Plugins
plugins:
  - search:
      lang:
        - en
  - minify:
     minify_html: true
  - git-revision-date-localized:
     type: datetime

extra_javascript:
    - assets/js/helpers.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
extra_css:
    - assets/stylesheets/extra.css
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
    - https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css


# These extensions are chosen to be a superset of Pandocs Markdown.
# This way, I can write in Pandocs Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.snippets:
        base_path: ["."]
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
    - md_in_html



nav:
  - Home: index.md
 